### ISSUE TITLE
Assets/Advanced Playground/Gallery/Gallery.cs(8,26): error CS0246: The type or namespace name 'NFTs_OfAContract' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by Hye1Kim** [nftport/nftport-unity#23]
Hi,
After updating the package to 1.0.0 the following problems occurred.
![Screenshot from 2022-10-06 14-40-18](https://user-images.githubusercontent.com/102787163/194229052-00040fbf-c32d-4b7c-9295-ff4ceee9c6d4.png)

[details]
Assets/Advanced Playground/Gallery/Gallery.cs(8,26): error CS0246: The type or namespace name 'NFTs_OfAContract' could not be found (are you missing a using directive or an assembly reference?)

Assets/Advanced Playground/Gallery/GalleryController.cs(104,12): error CS0246: The type or namespace name 'NFTs_OfAContract' could not be found (are you missing a using directive or an assembly reference?)

Assets/Advanced Playground/Gallery/Gallery.cs(16,22): error CS0246: The type or namespace name 'NFTs_OfAContract' could not be found (are you missing a using directive or an assembly reference?)

**Comment by saszer** [comment]
V1 onwards, NFTs_OfAContract has been renamed to NFTs_OfACollection and also functions have been combined to make it more unified across different chains and networks outside Ethereum. 

Refactored:

```
        NFTs_OfACollection
            .Initialize(destroyAtEnd:true)
            .SetChain(NFTs_OfACollection.Chains.polygon)
            .SetParameters(
                    collection: "0x42b57de948d05d17fb11d4e527df80a0420a4392", 
                    include: NFTs_OfACollection.Includes.all
                    )
            .OnError(error=>Debug.Log(error))
            .OnComplete(NFTs=> collectionNFTs = NFTs)
            .Run();
```
Refer docs >
https://docs.nftport.xyz/docs/nftport/ZG9jOjk0NjM3NjA1-nf-ts-of-a-collection

**Comment by saszer** [comment]
[Metaverse template sample ](https://github.com/nftport/sample-unity3D-nft-metaverse-template) is yet to be updated for V1.
